apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-1

nodeGroups:
  - name: react-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
  - name: react-2
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 100
