version: 2.1

orbs:
  docker: circleci/docker@0.5.13

commands:
  default-configuration:
    description: preparing the containers with dependencies to deploy front and back end
    steps:
      - run:
          name: Install curl, tar and gzip
          command: |
            echo installing curl, tar and gzip
            apk add --update tar gzip curl
      - run:
          name: Install ansible
          command: |
            echo Installing ansisble
            apk add --update ansible
      - run:
          name: Install nodejs and npm
          command: |
            echo installing nodejs and npm
            apk add --update nodejs npm
      - run:
          name: Install aws cli
          command: |
            echo installing awscli
            pip install awscli

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:14.17.6

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fc:54:cd:b6:ea:2e:8f:2d:52:15:75:8b:ee:47:c1:39"]
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - dist
      - run:
          name: test
          command: npm test

  # deploy:
  #   docker:
  #     - image: python:3.7-alpine3.11
  #   steps:
  #     - checkout
  #     - default-configuration
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         # name: update s3
  #         # command: |
  #         #   tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
  #         #   aws s3 cp dist s3://my-app-udacity-sb --recursive
  #         name: ansible playbook run
  #         command: |
  #           ansible-playbook .circleci/ansible/setup.yml

  deploy:
    docker:
      - image: alpine/k8s:1.15.12
    working_directory: /tmp/workspace
    steps:
      - checkout
      # - run:
      #     name: store current cluster name
      #     command: |
      #       echo $(aws eks list-clusters | python3 -c "import sys, json; print(json.load(sys.stdin)['clusters'][0])") > cluster-old.txt
      #       cat cluster-old.txt
      # - run:
      #     name: create new kubernetes cluster
      #     command: |
      #       # Updating the cluster name in the Yaml
      #       # sed -i "s/basic-cluster/udacity-capstone-${CIRCLE_SHA1:0:7}/g" cluster.yml
      #       sed -i "s/basic-cluster/udacity-capstone-140814a/g" cluster.yml
      #       eksctl create cluster -f cluster.yml
      # - run:
      #     name: store new cluster name
      #     command: |
      #       echo "udacity-capstone-${CIRCLE_SHA1:0:7}" > cluster.txt
      #       cat cluster.txt
      - run:
          name: Deploy Application on Kubernetes
          command: |
            # aws eks update-kubeconfig --name "udacity-capstone-${CIRCLE_SHA1:0:7}"
            aws eks update-kubeconfig --name "udacity-capstone-140814a"
            export KUBECONFIG=/root/.kube/config
            kubectl get svc
            kubectl apply -f deployment/
            kubectl rollout status deployment react-web-app
      - run:
          name: Add service ip to a file
          command: |
            echo "$(kubectl get services react-web-app-service --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')" > service.txt
            cat service.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - cluster.txt
            - cluster-old.txt
            - service.txt

workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      - docker/publish:
          image: seandbull/$CIRCLE_PROJECT_REPONAME
          dockerfile: dockerfile
          requires:
            - run_tests
          filters:
            branches:
              only:
                - docker
      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - main
