---
- name: Run apt upgrade
  apt:
    upgrade: "yes"
    update_cache: yes

- name: Installing Prerequisites for Kubernetes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
      - conntrack
    state: present

- name: add Kubernetes apt-key for APT repository
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
    mode: 0600

- name: install kubelet, kubeadm, and kubectl
  apt:
    force_apt_get: yes
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Enable service kubelet, and enable persistently
  service:
    name: kubelet
    enabled: yes

- name: configure Kubernetes cgroup driver to match Docker's (cgroupfs)
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: "^ExecStart"
    firstmatch: yes
    line: 'Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"'
    state: present

- name: reload daemon
  command: systemctl daemon-reload

- name: restart kubelet
  command: systemctl restart kubelet

# - name: Installing conntrack
#   yum:
#     name: conntrack
#     state: present

- name: Downloading minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: ~/
- name: copy and make dir
  command: |
    sudo cp minikube-linux-amd64 /usr/local/bin/minikube
    sudo chmod +x /usr/local/bin/minikube

#     # sudo mkdir -p usr/local/bin/minikube
# - name: Installing minkube
#   yum:
#     name: ~/minikube-linux-amd64
#     state: present

- name: Starting Minikube driver using none
  command: minkube start --driver=none

- name: conf repo for kubectl
  yum_repository:
    name: Kubernetes
    description: Kubectl
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes

- name: kubectl run
  command: minikube kubectl -- run project4 --image={{ default_container_image }}:{{  defualt_container_tag  }}

- name: list pods
  command: minikube kubectl -- get pods

- name: open ports
  command: minikube kubectl -- port-forward project4 8000:80
