apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web-app
spec:
  selector:
    matchLabels:
      app: react-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: react-web-app
    spec:
      containers:
        - name: react-web-app
          image: seandbull/my-app:0834d9a4212963129759eb1f35c3efd090266ab8
          ports:
            - containerPort: 80
