apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-my-app
spec:
  selector:
    matchLabels:
      app: react-my-app
  replicas: 2
  template:
    metadata:
      labels:
        app: react-my-app
    spec:
      containers:
        - name: react-my-app
          image: seandbull/my-app:latest
          ports:
            - containerPort: 80
