apiVersion: v1
kind: Service
metadata:
  name: service-react-my-app
  labels:
    name: react-my-app
spec:
  selector:
    app: react-my-app
  ports:
    - name: http
      port: 8000
      targetPort: 80
  type: LoadBalancer
